### ISSUE TITLE
cannot import client

### ISSUE THREAD

**Issue by studentdave** [pinecone-io/pinecone-client#20]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I have pinecone installed, (no errors or issues)
pip3 install pinecone-client

but following the readme here:
from pinecone import Client, Vector
ImportError: cannot import name 'Client' from 'pinecone' (/home/jupyter/.local/lib/python3.9/site-packages/pinecone/__init__.py)

i cannot find any reason for this error except that "client" doesn't exist. 

### Expected Behavior

i should be able to import Client

### Steps To Reproduce

from pinecone import Client, Vector

### Environment

```markdown
Python 3.9.16
Version: 2.2.2
```

**Comment by miararoy** [comment]
Hi @studentdave 

Note that correct install for this client is:
`pip3 install pinecone-client==3.0.0rc2`

Both clients are directing at the same Pypi project, with this being an experimental version (though much more performant)
